import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Hero from "@/components/hero";
import Creators from "@/components/creators";
import Categories from "@/components/categories";
import Collection from "@/components/collection";
import More from "@/components/more";
import Works from "@/components/works";
import Digest from "@/components/digest";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
          <main>
            {children}
            <Hero />
            <Collection />
            <Creators />
            <Categories />
            <More />
            <Works />
            <Digest />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
